# Generated by Django 6.0.2 on 2026-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='ap_2p6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloco',
            name='inicio_numeracao',
            field=models.PositiveIntegerField(default=1, help_text='Qual é o primeiro apartamento? ex: 101'),
        ),
        migrations.AddField(
            model_name='bloco',
            name='qtd_andares',
            field=models.PositiveIntegerField(default=0, help_text='Quantos andares tem o prédio?'),
        ),
        migrations.AddField(
            model_name='bloco',
            name='qtd_ap_por_andar',
            field=models.PositiveIntegerField(default=0, help_text='Quantos apartamentos por andar?'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='naturgy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
