# Generated by Django 6.0.2 on 2026-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apartamento_ap_2p6_bloco_inicio_numeracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='qtd_andares_padrao',
            field=models.PositiveIntegerField(default=0, help_text='Padrão para os blocos deste condomínio'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='qtd_ap_por_andar_padrao',
            field=models.PositiveIntegerField(default=0, help_text='Padrão de aptos por andar'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='inicio_numeracao',
            field=models.PositiveIntegerField(blank=True, help_text='Qual é o primeiro apartamento? ex: 101', null=True),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='qtd_andares',
            field=models.PositiveIntegerField(blank=True, help_text='Quantos andares tem o prédio?', null=True),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='qtd_ap_por_andar',
            field=models.PositiveIntegerField(blank=True, help_text='Quantos apartamentos por andar?', null=True),
        ),
    ]
