# Generated by Django 6.0.2 on 2026-02-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_condominio_qtd_andares_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Serviço'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Serviço'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='inicio_numeracao',
            field=models.PositiveIntegerField(default=101, help_text='Qual é o primeiro apartamento? ex: 101'),
        ),
    ]
