# Generated by Django 6.0.2 on 2026-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_condominio_data_fim_condominio_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartamento',
            options={'ordering': ['numero']},
        ),
        migrations.AddField(
            model_name='apartamento',
            name='arquivo_os',
            field=models.FileField(blank=True, null=True, upload_to='os/'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='arquivo_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
