# Generated by Django 6.0.2 on 2026-02-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_apartamento_options_apartamento_arquivo_os_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamento',
            name='arquivo_os',
        ),
        migrations.RemoveField(
            model_name='apartamento',
            name='arquivo_video',
        ),
        migrations.AddField(
            model_name='apartamento',
            name='equipamento',
            field=models.CharField(blank=True, help_text='Ex: Fogão 4 bocas, Aquecedor Lorenzetti', max_length=200, verbose_name='Equipamento(s)'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='morador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Morador'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações / Impedimentos'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='tecnico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Técnico Responsável'),
        ),
        migrations.CreateModel(
            name='ArquivoApartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/apartamentos/')),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('OS', 'Ordem de Serviço'), ('EXTRA', 'Foto/Doc Extra')], max_length=10)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.apartamento')),
            ],
        ),
    ]
