# Generated by Django 6.0.2 on 2026-02-24 14:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_apartamento_arquivo_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoapartamento',
            name='arquivo',
            field=models.FileField(upload_to=core.models.caminho_arquivo_personalizado),
        ),
    ]
