# Generated by Django 6.0.2 on 2026-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_arquivoapartamento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='exaustao_forcada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arquivoapartamento',
            name='tipo',
            field=models.CharField(choices=[('VIDEO', 'Vídeo'), ('OS', 'Ordem de Serviço'), ('EXTRA', 'Foto/Doc Extra'), ('OS_EX', 'OS Exaustão')], max_length=10),
        ),
    ]
