# Generated by Django 6.0.2 on 2026-02-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_apartamento_exaustao_forcada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='qtd_saloes_festas',
            field=models.PositiveIntegerField(default=0, help_text='Cria automaticamente um bloco de Áreas Comuns', verbose_name='Qtd. Salões de Festas'),
        ),
    ]
