# Generated by Django 6.0.2 on 2026-02-24 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_condominio_qtd_saloes_festas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Equipes/Usuários restritos apenas a este bloco.', related_name='blocos_atribuidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condominio',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Usuários que podem ver TODOS os blocos deste condomínio.', related_name='condominios', to=settings.AUTH_USER_MODEL),
        ),
    ]
